# Generated by Django 3.1.5 on 2021-04-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('RegNo', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=40)),
                ('current_GPA', models.CharField(max_length=20)),
            ],
        ),
    ]
